[package]
name = "solana-account-info"
description = "Solana AccountInfo and related definitions."
documentation = "https://docs.rs/solana-account-info"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true, default-features = false, optional = true }
serde = { workspace = true, default-features = false, optional = true }
solana-program-error = { workspace = true, default-features = false }
solana-program-memory = { workspace = true, default-features = false }
solana-pubkey = { workspace = true, default-features = false }
solana-bincode = { workspace = true, default-features = false }

[features]
std = []
bincode = ["dep:bincode", "dep:serde"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
